[package]
name = "ndlc"
version = "0.1.0"
edition = "2021"

[dependencies]
lang-c = "0.15.1"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
serde_with = "3.8.3"
